### ISSUE TITLE
Image not showing in UG 

### ISSUE THREAD

**Issue by LeeJoonJie** [AY2021S1-CS2103T-T15-1/tp#270]
Hi, I was looking at your UG and found a bug. In section 4.5.3 List all shortcuts, an image was not showing. Please see the photo. 

<img width="732" alt="Screenshot 2020-11-07 at 6 34 49 PM" src="https://user-images.githubusercontent.com/48320865/98438890-572e6980-2128-11eb-86cd-6d16b88f7148.png">

**Comment by pooty3** [comment]
Thank for helping us find the bug!
