### ISSUE TITLE
Image not showing in DG

### ISSUE THREAD

**Issue by LeeJoonJie** [AY2021S1-CS2103T-T15-1/tp#271]
Hi, I was looking at your DG and found a bug. In the Command Shortcut feature section, an image was not showing. Please see the photo.

<img width="803" alt="Screenshot 2020-11-07 at 6 41 23 PM" src="https://user-images.githubusercontent.com/48320865/98438982-46cabe80-2129-11eb-80f1-4cee3d790f40.png">

**Comment by pooty3** [comment]
Thanks for helping us find the bug!
